<a href="https://colab.research.google.com/github/soumilhooda/MLDLNNtoCV/blob/main/Q1_NNFL_Assignment2_SoumilHooda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


Now we shall import our standard packages for easier data handling and mathematical computations.

In [12]:
import pandas as pd
import numpy as np
import math 
import matplotlib.pyplot as plt
import numpy.random as nr
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
np.random.seed(0)
from sklearn.metrics import confusion_matrix

In [27]:
data = pd.read_excel('/content/drive/MyDrive/data55.xlsx',header=None)
data_values = data.values


In [28]:
xdata, ydata = data_values[... , :60], data_values[... , 60: ]
print(xdata)
print(xdata.shape)
print(ydata)
print(ydata.shape)

[[0.02   0.0371 0.0428 ... 0.0084 0.009  0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 ...
 [0.0522 0.0437 0.018  ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049  ... 0.0079 0.0036 0.0048]
 [0.026  0.0363 0.0136 ... 0.0036 0.0061 0.0115]]
(208, 60)
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]


In [29]:
x_train, _x, y_train, _y = train_test_split(xdata, ydata, test_size=0.30)
x_test, x_val, y_test, y_val = train_test_split(_x, _y, test_size=0.33)

print(x_train.shape)
print(x_test.shape)
print(x_val.shape)

(145, 60)
(42, 60)
(21, 60)


In [14]:
w = np.random.rand(60)
print(w.shape)

b = np.random.rand(1)
print(b.shape)

(60,)
(1,)


In [30]:
def NonLinearPerceptron_Train(iters, w, b, x_train, y_train):
  w = np.random.rand(60)
  print(w.shape)

  b = np.random.rand(1)
  print(b.shape)
  for j in range(iters):
    for i in range(x_train.shape[0]):
      h = np.sign(np.dot(w, x_train[i])+ b)
      if (h != y_train[i]):
        w = w + y_train[i]*x_train[i]
        b = b + y_train[i]
  return w, b

In [31]:
iters = 10000
w_aftertrain, b_aftertrain = NonLinearPerceptron_Train(iters, w, b, x_train, y_train)

print(w)
print(w_aftertrain)
print(b_aftertrain)

(60,)
(1,)
[9.92396399e-01 2.67262538e-01 6.79090616e-01 8.64281443e-01
 7.50844246e-01 9.64489768e-01 5.54242435e-01 2.12390499e-01
 2.22443224e-01 2.18749374e-01 5.69573535e-01 4.52109035e-01
 9.70236683e-01 6.80544691e-01 8.52955659e-02 5.64183327e-02
 4.87837704e-01 8.81004562e-01 9.76404387e-01 6.17657916e-01
 5.42498775e-01 8.54613580e-01 7.43834545e-01 4.78596326e-01
 6.77081574e-01 6.07045061e-01 7.14696936e-01 4.69497183e-01
 4.56014623e-01 9.06418087e-01 1.37220420e-01 2.29219323e-01
 8.81585399e-01 9.04424976e-01 6.45784599e-01 3.24682972e-01
 5.19711194e-01 5.53568650e-05 3.11860221e-01 4.25451538e-01
 8.85337660e-01 6.79879456e-01 4.56129772e-01 4.83408617e-01
 7.88739428e-01 2.29441834e-01 8.80297603e-01 3.13692393e-01
 9.57450856e-01 4.71751571e-01 7.11583817e-01 1.53694305e-01
 7.30442177e-01 6.46264437e-01 2.14880737e-01 1.86458219e-01
 8.07580269e-01 7.47079470e-01 6.74847346e-01 2.76893751e-01]
[3.57424652e-01 6.21665436e-01 2.88569958e-01 8.74399917e-01
 1.12427317e

In [33]:
z = np.dot(x_test, w_aftertrain.T) + b
print(z)
print(y_test)
print(z.shape)
print(z)
z_min = np.min(z)
z_max = np.max(z)
h = (z - z_min)/(z_max - z_min)
y_pred=h>0.5
y_pred=y_pred.astype(int)
print(y_pred)
cm=confusion_matrix(y_test, y_pred)
print(cm)
accuracy=(cm[0][0]+cm[1][1])/(len(y_test))
print(accuracy)

[ 8.1396619  10.18768768  9.06102345  5.8876805   8.91310683  7.47349502
  9.20752138  8.67555646  8.62785912  8.64731023  7.12222971 10.51048136
  7.441471    8.62687156  8.78196232  5.76768916  8.51176119  9.25632015
  7.8293526   7.89095642  8.39138496  8.61397135  8.0128785   7.5827327
  9.61886408  7.36312459  9.28251038  9.59232541  7.30426964  7.77078267
  9.52147693  7.8507423   9.07613202 10.82591128 10.75233879 10.21179972
  7.5387034   8.49029663  8.86885841  5.7394403   9.96028724  8.4236859 ]
[[0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]]
(42,)
[ 8.1396619  10.18768768  9.06102345  5.8876805   8.91310683  7.47349502
  9.20752138  8.67555646  8.62785912  8.64731023  7.12222971 10.51048136
  7.441471    8.62687156  8.78196232  5.76768916  8.51176119  9.25632015
  7.8293526