<a href="https://colab.research.google.com/github/soumilhooda/MLDLNNtoCV/blob/main/Q2_NNFL_Assignment2_SoumilHooda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving data55.xlsx to data55.xlsx


In [2]:
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.model_selection import train_test_split #To split the dataset

In [3]:
def sigmoid(z):
  z = z.astype(float)
  s = 1/(1 + np.exp(-z))
  return s


In [4]:
def cost_func(X,y,w,lam):
  hypothesis = sigmoid(np.dot(X,w.T))
  J = (-1/len(y))*np.sum(y*np.log(hypothesis) + (1-y)*(np.log(1-hypothesis)))
  return J

In [5]:
def BGD(X,y,w,lam,alpha,iters):
  cost_history = np.zeros(iters)
  for i in range(iters):
    hypothesis = sigmoid(np.dot(X,w.T))
    w = w - (alpha/len(y))*np.dot((hypothesis - y), X)
    cost_history[i] = cost_func(X,y,w,lam)
  return w , cost_history

In [6]:
def MBGD(X,y,w,lam,alpha,iters,batch_size):
  cost_history = np.zeros(iters)
  for i in range(iters):
    rand_index = np.random.randint(len(y))
    ind_x = X[rand_index:rand_index + batch_size]
    ind_y = y[rand_index:rand_index + batch_size]
    w = w - (alpha/batch_size)*(ind_x.T.dot(sigmoid(ind_x.dot(w)) - ind_y))
    cost_history[i] = cost_func(ind_x,ind_y,w,lam)
  return w , cost_history

In [7]:
def SGD(X,y,w,lam,alpha,iters):
  cost_history = np.zeros(iters)
  for i in range(iters):
    rand_index = np.random.randint(len(y))
    ind_x = X[rand_index:rand_index+1]
    ind_y = y[rand_index:rand_index+1]
    w = w - alpha*(ind_x.T.dot(sigmoid(ind_x.dot(w)) - ind_y))
    cost_history[i] = cost_func(ind_x,ind_y,w,lam)
  return w , cost_history

In [8]:
dataset = pd.read_excel('data55.xlsx')
dataset

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
203  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

     0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4    0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
202  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
203  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
204  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
205  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
206  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

     0.0090  0.0032  0.0000  
0    0.0052  0.0044     0.0  
1    0.0095  0.0078     0.0  
2    0.0040  0.0117     0.0  
3    0.0107  0.0094     0.0  
4    0.0051  0.0062     0.0  
..      ...     ...     ...  
202  0.0193  0.0157     1.0  
203  0.0062  0.0067     1.0  
204  0.0077  0.0031     1.0  
205  0.0036  0.0048     1.0  
206  0.0061  0.0115     1.0  

[207 rows x 61 columns]

In [11]:
datasetn = dataset.values
X = datasetn[ : , 0:60]
y = datasetn[:,60]

In [12]:
#Splitting the Data
X_train, X_rem, y_train, y_rem = train_test_split(X,y, train_size=0.7, random_state= 10 )
X_test, X_valid, y_test, y_valid = train_test_split(X_rem, y_rem, train_size=0.6666, random_state = 10)

#Normalization and setting up the features
xmin = np.min(X_train, axis = 0)
xmax = np.max(X_train, axis = 0)
X_train = (X_train - xmin)/(xmax-xmin)
X_test = (X_test - xmin)/(xmax-xmin)
X_valid = (X_valid - xmin)/(xmax-xmin)
m_train = X_train.shape[0]
m_test = X_test.shape[0]
m_valid = X_valid.shape[0]
X_train = np.append(np.ones([m_train,1]),X_train,axis = 1)
X_test = np.append(np.ones([m_test,1]),X_test,axis = 1)
X_valid = np.append(np.ones([m_valid,1]),X_valid,axis = 1)
print(X_valid)

[[1.         0.05572065 0.06632214 ... 0.09382151 0.10743802 0.25635104]
 [1.         0.051263   0.06416882 ... 0.19221968 0.20936639 0.26789838]
 [1.         0.18499257 0.09689922 ... 0.36155606 0.60330579 0.38568129]
 ...
 [1.         0.14264487 0.05813953 ... 0.04347826 0.05785124 0.06004619]
 [1.         0.20653789 0.14470284 ... 0.17391304 0.09641873 0.09699769]
 [1.         0.45319465 0.29801895 ... 0.18764302 0.10743802 0.1039261 ]]


In [13]:
def linear_kernel(x1, x2):
    return np.dot(x1, x2)

In [14]:
def polynomial_kernel(x, y, p=3):
    return (1 + np.dot(x, y)) ** p

In [15]:
class KernelPerceptron(object):
    def __init__(self, kernel=linear_kernel, T=1):
        self.kernel = kernel
        self.T = T

    def fit(self, X, y):
        n_samples, n_features = X.shape
        #np.hstack((X, np.ones((n_samples, 1))))
        self.alpha = np.zeros(n_samples, dtype=np.float64)

        # Gram matrix
        K = np.zeros((n_samples, n_samples))
        for i in range(n_samples):
            for j in range(n_samples):
                K[i,j] = self.kernel(X[i], X[j])

        for t in range(self.T):
            for i in range(n_samples):
                if np.sign(np.sum(K[:,i] * self.alpha * y)) != y[i]:
                    self.alpha[i] += 1.0

        # Support vectors
        sv = self.alpha > 1e-5
        ind = np.arange(len(self.alpha))[sv]
        self.alpha = self.alpha[sv]
        self.sv = X[sv]
        self.sv_y = y[sv]
        print (len(self.alpha), n_samples)

    def project(self, X):
        y_predict = np.zeros(len(X))
        print(f'dataset points len: {len(X)}')
        for i in range(len(X)):
            # print('dbg3.2')
            s = 0
            for a, sv_y, sv in zip(self.alpha, self.sv_y, self.sv):
                s += a * sv_y * self.kernel(X[i], sv)
            y_predict[i] = s
        return y_predict

    def predict(self, X):
        X = np.atleast_2d(X)
        n_samples, n_features = X.shape
        #np.hstack((X, np.ones((n_samples, 1))))
        return np.sign(self.project(X))


In [16]:
def krnl_gen(X):
  krnl = X
  for i in range(60):
    for j in range(60):
      a = krnl[:,i]
      b = krnl[:,j]
      z = np.multiply(a,b)
      krnl = np.insert(krnl, 5, z, axis = 1)
  return krnl   

In [17]:
X_train = krnl_gen(X_train)
X_train

array([[1.        , 0.1307578 , 0.00387597, ..., 0.04805492, 0.15426997,
        0.08775982],
       [1.        , 0.17236256, 0.18518519, ..., 0.44851259, 0.69972452,
        0.40184758],
       [1.        , 0.51708767, 0.67054264, ..., 0.32951945, 0.42975207,
        0.28406467],
       ...,
       [1.        , 0.24294205, 0.04263566, ..., 0.02745995, 0.19834711,
        0.1408776 ],
       [1.        , 0.51263001, 0.3583118 , ..., 0.21967963, 0.22589532,
        0.27251732],
       [1.        , 0.01040119, 0.01981051, ..., 0.        , 0.14325069,
        0.06928406]])

In [18]:
w = np.zeros(X_train.shape[1])
print(w)

[0. 0. 0. ... 0. 0. 0.]


In [19]:
iters = 2000
def grid_search1(w,X,y):
  alpha_val = [0.01 , 0.05 , 0.1 , 0.15 , 0.2 , 0.5]
  lam_val = [0.05 , 0.1 , 0.15 , 0.2 , 0.5 , 1]
  max_w = w
  max_accuracy = 0
  for alpha in alpha_val:
    for lam in lam_val:
      w_temp , J_temp = BGD(X,y,w,lam,alpha,iters)
      m = y.shape[0]
      hypothesis = sigmoid(np.dot(X,w_temp.T))
      error = hypothesis - y
      accuracy = 100 - (np.mean(np.abs(hypothesis - y))*100)
      if max_accuracy < accuracy:
        max_accuracy = accuracy
        max_w = w_temp
  return max_w , max_accuracy

In [20]:
X_valid = krnl_gen(X_valid)
X_test = krnl_gen(X_test)

In [21]:
final_w , final_accuracy = grid_search1(w,X_valid,y_valid)
# print(final_w)
print(final_accuracy)

96.7420699747761


In [22]:
TN, FN, TP, FP = 0, 0, 0, 0
y_pred = np.dot(X_test, final_w)
y_pred = sigmoid(y_pred)
y_pred[y_pred > 0.5] = 1
y_pred[y_pred <= 0.5] = 0
TP = np.sum(y_pred * y_test)
FP = np.sum(y_pred * (1-y_test))
FN = np.sum((1-y_pred) * y_test)
TN = np.sum((1-y_pred) * (1-y_test))

In [23]:
sensitivity = TP/(TP + FN)
specificity = TN/(TN + FP)
accuracy = (TP + TN)/(TP + TN + FP + FN)
print(sensitivity, specificity, accuracy)

0.7 0.42857142857142855 0.5609756097560976
